name: 'Assign Reviewer'
description: ''
inputs:
    teamReviewers:
        required: false
    reviewers:
        required: false
    githubToken:
        required: true
outputs:
    time: # id of output
        description: 'The time we greeted you'
runs:
    using: 'node12'
    main: 'dist/index.js'
