name: Assign frontend reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo $CONTEXT
      - name: Dump2
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo "${CONTEXT}""
      - use: .github/actions/assign-reviewer
        with:
          team: 'team_frontend'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
