name: Assign frontend reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yaakaito/action-request-review@master
        id: request
        with:
          reviewers: gomazoa
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - if: "contains(steps.request.outputs.reviewers, '@')"
        env:
          REVIEWERS: ${{ steps.request.outputs.reviewers }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TITLE: ${{ github.event.pull_request.title }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl \
            -X POST\
            --data-urlencode "payload=\
                {\
                  \"channel\": \"#dev_null\", \
                  \"username\": \"Pull daNpa\",\
                  \"text\": \"${URL} ${REVIEWERS}\",\
                  \"icon_emoji\": \":pull_danpa:\"\
                  \"blocks\": [\
                    {\
                      \"type\": \"section\",\
                      \"text\": {\
                        \"type\": \"mrkdwn\",\
                        \"text\": \"Danny Torrence left the following review for your property:\"\
                      }\
                    }\
                  ]\
                }"\
            ${SLACK_WEBHOOK}
